import { PERMISSIONS } from '../../rbac/constants/permissions';
import { ROLES } from '../../rbac/constants/roles';

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,

    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_REMOVE,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,
    PERMISSIONS.AGENT_UPDATE,
    PERMISSIONS.AGENT_DELETE,

    PERMISSIONS.TOOL_CREATE,
    PERMISSIONS.TOOL_READ,
    PERMISSIONS.TOOL_UPDATE,
    PERMISSIONS.TOOL_DELETE,
    PERMISSIONS.TOOL_EXECUTE,

    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
    PERMISSIONS.WORKFLOW_DELETE,
    PERMISSIONS.WORKFLOW_EXECUTE,

    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,
    PERMISSIONS.AGENT_UPDATE,

    PERMISSIONS.TOOL_CREATE,
    PERMISSIONS.TOOL_READ,
    PERMISSIONS.TOOL_UPDATE,
    PERMISSIONS.TOOL_EXECUTE,

    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
    PERMISSIONS.WORKFLOW_EXECUTE,

    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,

    // No TOOL_* grants for members — tool config can hold real secrets
    // (e.g. an API key in `config.headers`), and GET /tools/:id returns
    // that config in full with no masking. Restricting to admin+owner is
    // the deliberate MVP posture; see the Phase 3 plan for the reasoning.

    // No WORKFLOW_EXECUTE for members — a run can trigger real outbound
    // tool calls and real OpenAI spend, same trust tier as TOOL_EXECUTE
    // above. Members can still design workflows (create/read), just not
    // run them.
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,

    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
  ],
};
