import { PERMISSIONS } from '../../rbac/constants/permissions';
import { ROLES } from '../../rbac/constants/roles';

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,

    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_REMOVE,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,
    PERMISSIONS.AGENT_UPDATE,
    PERMISSIONS.AGENT_DELETE,

    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
    PERMISSIONS.WORKFLOW_DELETE,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,
    PERMISSIONS.AGENT_UPDATE,

    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_UPDATE,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_READ,

    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_READ,
  ],
};
